---

# deletes a resource group in Azure. WARNING: This will delete all resources within the Resource Group

- hosts: localhost
  connection: local
  tasks:
    - name: Deleting resource group - "{{ name }}" - and its resources
      azure_rm_resourcegroup:
        name: "{{ name }}"
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg

...